// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑
// 🛑 THIS IS AN AUTOGENERATED FILE - DO NOT EDIT DIRECTLY 🛑
// 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑 🛑

// @ts-nocheck
/* eslint-disable */
export type CoercedEnvSchema = {
  /** **INFISICAL_CLIENT_ID** 🔐 _sensitive_ */
  INFISICAL_CLIENT_ID: string;

  /** **INFISICAL_CLIENT_SECRET** 🔐 _sensitive_ */
  INFISICAL_CLIENT_SECRET: string;

  /** **NUXT_PUBLIC_GITHUB_REPO_NAME** */
  NUXT_PUBLIC_GITHUB_REPO_NAME: string;

  /** **NUXT_PUBLIC_GITHUB_REPO_OWNER** */
  NUXT_PUBLIC_GITHUB_REPO_OWNER: string;

  /** **NUXT_PUBLIC_GITHUB_REPO_BRANCH** */
  NUXT_PUBLIC_GITHUB_REPO_BRANCH: string;

  /**
   * **NUXT_PUBLIC_SCRIPTS_GOOGLE_ANALYTICS_ID**
   * GA4 measurement ID consumed by @nuxt/scripts' googleAnalytics
   * registry. Loaded directly via gtag.js (no GTM).
   */
  NUXT_PUBLIC_SCRIPTS_GOOGLE_ANALYTICS_ID: string;

  /**
   * **NUXT_GITHUB_TOKEN** 🔐 _sensitive_
   * Personal access token used by the Octokit REST and GraphQL clients
   * in server/api/github.
   */
  NUXT_GITHUB_TOKEN: string;

  /**
   * **NUXT_APPLE_DEVELOPER_PRIVATE_KEY** 🔐 _sensitive_
   * PEM-encoded ES256 private key downloaded from the Apple Developer
   * portal. Usually provided as a single line with `\n` escapes.
   */
  NUXT_APPLE_DEVELOPER_PRIVATE_KEY: string;

  /** **NUXT_APPLE_DEVELOPER_KEY_ID** 🔐 _sensitive_ */
  NUXT_APPLE_DEVELOPER_KEY_ID: string;

  /** **NUXT_APPLE_DEVELOPER_TEAM_ID** 🔐 _sensitive_ */
  NUXT_APPLE_DEVELOPER_TEAM_ID: string;

  /** **NUXT_APPLE_MUSIC_USER_TOKEN** 🔐 _sensitive_ */
  NUXT_APPLE_MUSIC_USER_TOKEN: string;

  /** **NUXT_SITE_NAME** 🔐 _sensitive_ */
  NUXT_SITE_NAME: string;

  /** **NUXT_SITE_URL** 🔐 _sensitive_ */
  NUXT_SITE_URL: string;

  /** **NUXT_PUBLIC_APP_DOMAIN** */
  NUXT_PUBLIC_APP_DOMAIN: string;

  /**
   * **NUXT_PUBLIC_APP_DESCRIPTION**
   * Public site description used by @nuxtjs/seo head meta and
   * schema.org identity definition. Consumed on nuxt.config.ts:86
   * and :372.
   */
  NUXT_PUBLIC_APP_DESCRIPTION: string;

  /**
   * **NUXT_PUBLIC_APP_LOGO**
   * Public favicon / logo URL. Consumed on nuxt.config.ts:118 for
   * the apple-touch-icon link and :377 for schema.org identity.
   */
  NUXT_PUBLIC_APP_LOGO: string;

  /**
   * **NUXT_OG_IMAGE_SECRET** 🔐 _sensitive_
   * Secret used to sign generated og:image URLs. Must be at least
   * 32 characters for adequate HMAC strength.
   */
  NUXT_OG_IMAGE_SECRET: string;
};

type _CoercedEnvSchema_a15b10b6 = CoercedEnvSchema;

declare module "varlock/env" {
  export interface TypedEnvSchema extends Readonly<_CoercedEnvSchema_a15b10b6> {}
  export interface PublicTypedEnvSchema extends Readonly<
    Pick<
      _CoercedEnvSchema_a15b10b6,
      | "NUXT_PUBLIC_GITHUB_REPO_NAME"
      | "NUXT_PUBLIC_GITHUB_REPO_OWNER"
      | "NUXT_PUBLIC_GITHUB_REPO_BRANCH"
      | "NUXT_PUBLIC_SCRIPTS_GOOGLE_ANALYTICS_ID"
      | "NUXT_PUBLIC_APP_DOMAIN"
      | "NUXT_PUBLIC_APP_DESCRIPTION"
      | "NUXT_PUBLIC_APP_LOGO"
    >
  > {}
}

export type EnvSchemaAsStrings = {
  [Property in keyof CoercedEnvSchema]: CoercedEnvSchema[Property] extends string
    ? CoercedEnvSchema[Property]
    : CoercedEnvSchema[Property] extends boolean
      ? "true" | "false"
      : string;
};

type _EnvSchemaAsStrings_a15b10b6 = EnvSchemaAsStrings;
declare global {
  // add types for global import.meta.env
  interface ImportMetaEnv extends _EnvSchemaAsStrings_a15b10b6 {}
  interface ImportMeta {
    readonly env: ImportMetaEnv;
  }

  // add types for global process.env
  namespace NodeJS {
    interface ProcessEnv extends _EnvSchemaAsStrings_a15b10b6 {}
  }
}
