icon:
  name: "simple-icons:jetpackcompose"
  background: "#4285F4"
  colors:
    primary: "#4285F4"
    secondary: "#4285F4"
    tertiary: "#4285F4"
eyebrow: "Sprache"
title: "Jetpack Compose"
description: >-
  Ich habe Jetpack Compose das erste mal zusammen mit Kotlin im ÜK 335
  verwendet, wo wir eine Android App erstellt haben.
badges:
  - title: "Mobile"
  - title: "UI"
  - title: "Android"
    icon:
      name: "simple-icons:android"
links:
  - title: "Mehr erfahren"
    url: "https://developer.android.com/compose"
    icon:
      name: "sf-symbols:chevron.right"

i18n:
  en:
    eyebrow: "Language"
    description: >-
      I used Jetpack Compose for the first time together with Kotlin in ÜK
      335, where we created an Android app.
    links:
      - title: "Learn more"
  fr:
    eyebrow: "Langue"
    description: >-
      J'ai utilisé Jetpack Compose pour la première fois avec Kotlin dans le
      CI 335, où nous avons créé une application Android.
    links:
      - title: "En savoir plus"
  it:
    eyebrow: "Lingua"
    description: >-
      Ho usato Jetpack Compose per la prima volta insieme a Kotlin in ÜK
      335, dove abbiamo creato un'applicazione Android.
    links:
      - title: "Per saperne di più"
