icon:
  name: "sf-symbols:clock.arrow.trianglehead.2.counterclockwise.rotate.90"
eyebrow: "Automation"
title: "Automatisierungsprojekte im Banking-Bereich"
description: >-
  Hier durfte ich einen allgemeinen Einblick in die Automation und ihr Umfeld
  erhalten. Ich war aktiv dabei und habe gelernt, die einzelnen Banken mit
  Ranorex und UiPath zu testen und zu automatisieren. Ausserdem habe ich dabei
  ein wenig C# gelernt und mehr über das .NET Framework erfahren. Darin möchte
  ich mich in Zukunft noch verbessern!
badges:
  - title: "Automation"
  - title: "Banking"
  - title: "Testing"
  - title: "Ranorex"
  - title: "UiPath"
  - title: ".NET"
  - title: "C#"
    icon:
      name: "simple-icons-extended:csharp"
info:
  date:
    duration:
      from: "2022-02-01"
      to: "2022-07-01"
  supervisor: "Alessio Iantosca"
  location: "Zür-Pfi51"
  department: "SCS-B2B-TBS-TCS-ART-AAC"

i18n:
  en:
    title: "Automation Projects in the Banking Sector"
    description: >-
      Here I gained a general insight into automation and its environment. I
      was actively involved and learned to test and automate the individual
      banks with Ranorex and UiPath. I also picked up a bit of C# and learned
      more about the .NET Framework. That is something I want to get better at
      in the future!
  fr:
    eyebrow: "Automatisation"
    title: "Projets d'automatisation dans le secteur bancaire"
    description: >-
      Ici, j'ai pu obtenir un aperçu général de l'automatisation et de son
      environnement. J'ai participé activement et appris à tester et à
      automatiser les différentes banques avec Ranorex et UiPath. J'ai
      également appris un peu de C# et découvert le framework .NET. C'est un
      domaine dans lequel je veux encore progresser à l'avenir !
  it:
    eyebrow: "Automazione"
    title: "Progetti di automazione nel settore bancario"
    description: >-
      Qui ho ottenuto una panoramica generale sull'automazione e sul suo
      contesto. Ho partecipato attivamente e ho imparato a testare e
      automatizzare le singole banche con Ranorex e UiPath. Ho anche imparato
      un po' di C# e scoperto il framework .NET. È un ambito in cui voglio
      migliorare ancora in futuro!
