description: >-
  Entdecke meinen Weg als Softwareentwickler, mit Projekten, Fähigkeiten und
  meiner Leidenschaft für effiziente, benutzerorientierte Lösungen in der
  Webentwicklung und darüber hinaus.

i18n:
  en:
    description: >-
      Explore my journey as a Software Engineer, showcasing my skills, projects,
      and dedication to building efficient, user-centered solutions in web
      development and beyond.
  fr:
    description: >-
      Découvrez mon parcours en tant qu'ingénieur logiciel, avec des projets,
      des compétences et mon engagement pour des solutions efficaces et centrées
      sur l'utilisateur dans le développement web et au-delà.
  it:
    description: >-
      Esplora il mio percorso come ingegnere software, con progetti, competenze
      e dedizione a soluzioni efficienti e centrate sugli utenti nello sviluppo
      web e oltre.
